### ISSUE TITLE
Build Error on Raspberry Pi

### ISSUE THREAD

**Issue by trise-ne** [leonjza/trauth#3]
Hi @leonjza and **thanks** a lot for your great [blogpost](https://sensepost.com/blog/2020/building-a-hipster-aware-pi-home-server/#traefik)! I really liked your approach on network optimization and that's exactly what i was looking for.

When I came to your trauth implementation i got stuck on a build error. Probably that's an error on my side but i was wondering if you could help me out with some tipps.

**Error** thrown when trying to build trauth:

```
~/docker-apps/traefik $ docker-compose up --build

Building trauth
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/docker-build-git383071185/https:: no such file or directory

ERROR: Service 'trauth' failed to build
```

I am using **versions**:

```
docker-compose version 1.28.5
Docker version 20.10.5, build 55c4c88
Linux 5.10.23-v7l+ #1406 SMP Mon Mar 15 15:44:40 GMT 2021 armv7l GNU/Linux
```

my **docker-compose.yml** looks like that:

```
trauth:
    build:
      context: https://github.com/leonjza/trauth.git
      dockerfile: Dockerfile
    image: trauth:local
    container_name: trauth
    environment:
      - TRAUTH_DOMAIN=domain.com
      - TRAUTH_PASSWORD_FILE_LOCATION=./htpass
    volumes:
      - ./htpass:/htpass
    restart: unless-stopped    
    networks:
      - web
```

Is there something that i'm doing wrong? I've searched for a solution and even if there are some builds around, but was not successful. 

Thanks for your help!

**Comment by leonjza** [comment]
I am not 100% certain why it's failing for you. Considering that its complaining about symlinks, are any of your local files actually symlinks?

For reference, here is my "productions" trauth service, maybe it helps:

```yaml
  trauth:
    build:
      context: https://github.com/leonjza/trauth.git
      dockerfile: Dockerfile
    image: trauth:local
    container_name: trauth
    environment:
      - TRAUTH_DOMAIN=internal.<redact>.com
      - TRAUTH_PASSWORD_FILE_LOCATION=/config/htpass
    volumes:
      - ./htpass:/config/htpass
    restart: unless-stopped
    networks:
      - web
```
